### ISSUE TITLE
complete the testimonials section , testimonials are in the doc file

### ISSUE THREAD

**Issue by byteninjaa0** [ECELL-ABES/ecell-Website-v2#3]
![image](https://github.com/user-attachments/assets/bac17830-4f3e-4adc-80ec-47924eea8c1e)

https://docs.google.com/document/d/1FxLfqbsgUKHLVBLR3eUVJv1NppxD-Tc_gZWg5EJrC2g/edit?usp=sharing

**Comment by amit-gupta18** [comment]
I am working on it.

**Comment by byteninjaa0** [comment]
@amit-gupta18 we have only one column of testimonials , it is two in the prototype see https://ecellabesec.framer.ai/
